# -*- coding: utf-8 -*-
"""prac1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTWfqqbt4oIxSW-4yqkoMlDT01Ajqtry
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('/content/iris.csv')

print(dataset.head())
print(dataset.info())
print(dataset.describe())

# Plot 1: Histogram for a numeric column
plt.figure(figsize=(8, 6))
sns.histplot(dataset['sepal_length'], kde=True, color='blue')
plt.title('Histogram of sepal_length')
plt.xlabel('sepal_length')
plt.ylabel('Frequency')
plt.show()

plt.subplot(2,2,1)
plt.plot(dataset['sepal_length'],color='r',linestyle=':',linewidth=2,marker='o',label='Line')
plt.legend()

plt.subplot(2,2,1)
plt.plot(dataset['sepal_width'],color='g',linestyle=':',linewidth=2,marker='o',label='Line')
plt.legend()

plt.subplot(2,2,1)
plt.plot(dataset['petal_width'],color='b',linestyle=':',linewidth=2,marker='o',label='Line')
plt.legend()

plt.subplot(2,2,1)
plt.plot(dataset['petal_length'],color='y',linestyle=':',linewidth=2,marker='o',label='Line')
plt.legend()

x=dataset['sepal_length']
y=dataset['sepal_width']

x1=dataset['petal_length']
y1=dataset['petal_width']

plt.title('Sepal Vs Petal')
plt.xlabel('X axis')
plt.ylabel('Y Axis')

plt.scatter(x,y,c='r',label='Sepal length & width')
plt.scatter(x1,y1,c='g',label='Petal length & width')
#plt.legend()
plt.grid()
plt.show()

